steps:
  - id: "Decrypt keys"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - kms
      - decrypt
      - --ciphertext-file=client/.env.enc
      - --plaintext-file=client/.env
      - --location=global
      - --keyring=rentmindme
      - --key=firebase-token

  - id: "Install node_modules"
    name: "gcr.io/cloud-builders/npm"
    dir: "client"
    args: ["install", "--silent"]

  - id: "Build"
    name: "gcr.io/cloud-builders/npm"
    dir: "client"
    args: ["run", "build"]

  - id: "Deploy"
    name: "gcr.io/$PROJECT_ID/firebase"
    dir: "client"
    args: ["deploy", "-P", "app-dev-rentmindr", "--non-interactive"]
    secretEnv: ["FIREBASE_TOKEN"]

timeout: 1200s

secrets:
  - kmsKeyName: "projects/app-dev-rentmindr/locations/global/keyRings/rentmindme/cryptoKeys/client-deploy-token"
    secretEnv:
      FIREBASE_TOKEN: "CiQAxzHGhe3ET6Pzvu50kT4BqA/QfRgaLe3Ga7FSCv0dTBIFwgQSVwApqFnydae6+7GsIY2BmyFgwNOXHXVFoB71JABfviAqP1lSRvd2zyqv645YEWfJVBiEIvK2PA+LeKPyDIdsxG81qiEjIu6rL0O9bnUr63zfKVH0nV3xHg=="
