name: Client Tests (Dev)

on:
  pull_request:
    branches:
      - release/dev

jobs:
  changes_detected:
    name: Detect file changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - shell: bash
        run: |
          # Get a list of changed files (starting with `client/`)
          echo Starting
          DIFF_FILES=$(git diff --name-only origin/release/dev $GITHUB_SHA |
            grep '^client\/' |
            grep -v '\.gitignore$'
          )
          echo DIFF_FILES=$DIFF_FILES
          if [ -n "$DIFF_FILES" ];
            # Return "true" - changes detected in `client/`
            then echo 'true' >> did-client-change.txt
            # Return "false" - no changes in `client/`
            else echo 'false' >> did-client-change.txt
          fi
      - name: Upload change result for `client/**`
        uses: actions/upload-artifact@v1
        with:
          name: client-change
          path: did-client-change.txt

  lint:
    name: Runt Linter
    needs: changes_detected
    runs-on: ubuntu-latest
    steps:
      - name: Download change result
        uses: actions/download-artifact@v1
        with:
          name: client-change

      - name: Set client_changed output
        id: client_changed
        run: echo "::set-output name=CONTINUE::$(cat client-change/did-client-change.txt)"

      - uses: actions/checkout@v1

      - name: Setup Node
        if: steps.client_changed.outputs.CONTINUE == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install Dependencies
        if: steps.client_changed.outputs.CONTINUE == 'true'
        run: |
          cd client
          npm ci

      - name: Run Linter
        if: steps.client_changed.outputs.CONTINUE == 'true'
        run: |
          cd client
          npm run lint
        env:
          CI: true

  test:
    name: Run Tests
    needs: changes_detected
    runs-on: ubuntu-latest

    steps:
      - name: Download change result
        uses: actions/download-artifact@v1
        with:
          name: client-change

      - name: Set client_changed output
        id: client_changed
        run: echo "::set-output name=CONTINUE::$(cat client-change/did-client-change.txt)"

      - uses: actions/checkout@v1

      - name: Setup Node
        if: steps.client_changed.outputs.CONTINUE == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install Dependencies
        if: steps.client_changed.outputs.CONTINUE == 'true'
        run: |
          cd client
          npm ci

      - name: Run Tests
        if: steps.client_changed.outputs.CONTINUE == 'true'
        run: |
          cd client
          npm run test:ci
        env:
          CI|: true
