name: Deploy Firebase Functions

on:
  push:
    branches:
      - release/dev
    paths:
      - "server/firebase/**"
      - "!**.md"
      - "!.gitignore"

jobs:
  build:
    name: Deploy Dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install Dependencies
        run: |
          cd server/firebase
          npm ci
