name: Dev Deploy

on:
  push:
    tags:
      - deploy/dev
    paths-ignore:
      - "server/**"
      - "**.md"
      - ".gitignore"

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install Dependencies
        run: |
          cd client
          npm ci
      - name: Run Linter
        run: |
          cd client
          npm run lint
        env:
          CI: true
