name: Deploy Firebase Functions

on:
  push:
    branches:
      - release/dev
    paths:
      - "server/firebase/**"
      - dev_deploy_functions.yml
      - "!**.md"
      - "!.gitignore"

jobs:
  build:
    name: Deploy Dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Get changed files
        id: changed_files
        run: echo "::set-output name=DEPLOY_REQUIRED::$(./.github/scripts/deploy_changed_functions.sh)"
        env:
          SOURCE_BRANCH: release/dev
          CURRENT_COMMIT: ${{ secrets.GITHUB_SHA }}

      - name: Print functions to be deployed
        run: echo ${{ steps.changed_files.outputs.DEPLOY_REQUIRED }}

      - name: Setup Node
        if: steps.changed_files.outputs.DEPLOY_REQUIRED != 'abort'
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install Dependencies
        if: steps.changed_files.outputs.DEPLOY_REQUIRED != 'abort'
        run: |
          cd server/firebase
          npm ci

      - name: Build
        if: steps.changed_files.outputs.DEPLOY_REQUIRED != 'abort'
        run: |
          cd server/firebase
          npm run funcs:clean
          npm run funcs:build

      - name: Deploy
        if: steps.changed_files.outputs.DEPLOY_REQUIRED != 'abort'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only ${{ steps.changed_files.outputs.DEPLOY_REQUIRED }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: "server/firebase"
