name: Deploy

on:
  pull_request:
    branches:
      - release/dev
    paths-ignore:
      - "server/**"
      - "**.md"
      - ".gitignore"

  push:
    branches:
      - release/dev
    paths-ignore:
      - "server/**"
      - "**.md"
      - ".gitignore"

jobs:
  build:
    name: Deploy Dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Decrypt config
        run: ./.github/scripts/decrypt_dev.sh
        env:
          CI: true
          DEV_CONFIG_PASSPHRASE: $

      - name: Test printing your secret (Remove)
        run: cat $HOME/secrets/config.dev.json
