name: Tests Pass

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-verion: "10.x"

      - name: cd into /client
        run: cd client

      - name: Install Dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run Linter
        run: npm install lint
# name: Tests Pass

# on:
#   pull_request:
#     branches:
#       - master
#       - release/production

# jobs:
#   lint:
#     name: Run Linter
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [10.x]

#     steps:
#       - uses: actions/checkout@v1
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: npm install and test
#         run: |
#           cd client
#           npm install
#           npm run lint
#         env:
#           CI: true

#   test:
#     name: Run Tests
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [10.x]

#     steps:
#       - uses: actions/checkout@v1
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: npm install and test
#         run: |
#           cd client
#           npm install
#           npm run test:ci
#         env:
#           CI: true
