name: Tests Pass

on:
  pull_request:
    branches:
      - master
      - release/production

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install Dependencies
        run: |
          cd client
          npm ci
      - name: Run Linter
        run: npm run lint
        env:
          CI: true

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install Dependencies
        run: |
          cd client
          npm ci
      - name: Run Tests
        run: npm run test:ci
        env:
          CI: true
